# Generated by Django 5.2.14 on 2026-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pdf_file", models.FileField(upload_to="exams/pdfs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
