# Generated by Django 5.2.14 on 2026-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_rename_created_at_exam_created_date_exam_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="pdf_file",
            field=models.FileField(upload_to="media/exams/pdfs/"),
        ),
    ]
