# Generated by Django 5.2.14 on 2026-05-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_exam_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multi_choice", "5-Choice Question"),
                            ("true_false_set", "5-Boolean Statements"),
                            ("numeric", "Numeric Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("correct_answer", models.CharField(max_length=50)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.exam",
                    ),
                ),
            ],
        ),
    ]
