# Generated by Django 5.2.14 on 2026-05-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexam",
            old_name="created_date",
            new_name="started_date",
        ),
        migrations.AddField(
            model_name="exam",
            name="multi_choice_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="numeric_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="true_false_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_value", models.CharField(max_length=10)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.question"
                    ),
                ),
                (
                    "user_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.userexam",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_exam", "question")},
            },
        ),
    ]
