# Generated by Django 5.2.14 on 2026-05-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_rename_created_date_userexam_started_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.RemoveField(
            model_name="exam",
            name="multi_choice_count",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="numeric_count",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="true_false_count",
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Question order in exam"
            ),
        ),
    ]
