# Generated by Django 5.2.14 on 2026-05-24 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="duration_lenght",
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name="exam",
            name="tag",
            field=models.CharField(default=django.utils.timezone.now, max_length=2001),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="end_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
