# Generated by Django 5.2.14 on 2026-05-24 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_exam_duration_lenght_exam_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="tag",
            field=models.CharField(default="", max_length=200),
        ),
    ]
