# Generated by Django 5.2.14 on 2026-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_alter_exam_created_date_alter_exam_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
