# Generated by Django 5.2.14 on 2026-05-24 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("M1", "Marhale 1"), ("M2", "Marhale 2")],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="question_count",
            field=models.PositiveIntegerField(default=25),
        ),
    ]
