# Generated by Django 5.2.14 on 2026-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0010_exam_exam_type_exam_question_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexam",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userexam",
            name="percentage_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="userexam",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="userexam",
            name="total_possible_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
