# Generated by Django 5.2.14 on 2026-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0011_userexam_completed_at_userexam_percentage_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="answer_value",
            field=models.CharField(blank=True, default="-", max_length=10),
        ),
    ]
