# Generated by Django 5.2.14 on 2026-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_alter_useranswer_answer_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexam",
            name="started_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
