# Generated by Django 5.2.14 on 2026-05-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0013_alter_userexam_started_date"),
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "percentage_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreboards",
                        to="exam.exam",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoreboard_entries",
                        to="personal.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "rank"],
                "unique_together": {("exam", "profile")},
            },
        ),
    ]
