# Generated by Django 5.2.14 on 2026-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0014_scoreboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
