# Generated by Django 5.2.14 on 2026-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0015_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="answer_pdf_file",
            field=models.FileField(default="", upload_to="media/exams/pdfs/a/"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="pdf_file",
            field=models.FileField(upload_to="media/exams/pdfs/q/"),
        ),
    ]
