# Generated by Django 5.2.14 on 2026-05-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0010_exam_exam_type_exam_question_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "user_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam.useranswer",
                    ),
                ),
            ],
        ),
    ]
